---
language: python
dist: xenial 
python:
    - "3.6"
    - "3.7"
install:
    - pip3 install nose2 taskw daemon timeloop
addons:
    apt:
      packages:
        - make 
        - task
jobs:
    include:
        - stage: Functional Testing
          script: 
            - make test
stages:
    - name: Functional Testing
      if: branch = devel 

